Personlist tasks
fl6-team-project/ng-project pull request #7
Opened 2017-03-23 09:51 UTC by melineWb

2017-03-23 09:55 UTC, dmk1111 reviewed
I think it would be better to use `api/lectures/last` instead of `api/lectureslast` in component & router;
`api/tasks/` instead of `api/recenttasks` as you filter them in `GET`-request after that

2017-03-23 20:13 UTC, statyan commented
Agree with @dmk1111 , last and recent are filter parameters for the list data, while state is used to display a list itself

2017-03-23 20:38 UTC, statyan requested changes

2017-03-23 20:38 UTC, statyan commented on client/src/components/closedTasksController.js
> +    tasks = tasks.filter((item) => {
Filtering should be done on a server side. We do not need to send the whole data through the network, when we need only several recent items

2017-03-23 20:38 UTC, statyan commented on client/src/components/closedTasksController.js
> +function recentTasksController($http) {
file is named "closedTasksController" while controller function is named "recentTasksController". Please use the equal naming to avoid confusion.

2017-03-23 20:38 UTC, statyan commented on client/src/components/recentTaskItem.html
> +  <input type="checkbox" id="{{task._id}}" ng-if="task.status === 'active'"/>
we can replace this with one input: 
`<input` type="checkbox" id="{{task._id}}" checked="{{task.status === 'done' ? 'checked' : ''}}"/>`

2017-03-23 20:38 UTC, statyan commented on client/src/components/recentTasksController.js
> +      if (item.status == 'active') {
Filtering for most cases should be done on a server side

2017-03-23 20:38 UTC, statyan commented on client/src/components/recentTasksController.js
> +      if (item.status == 'active') {
Or you can retrieve all tasks, but filter it on tab change and do not send additional requests to server

2017-03-23 20:38 UTC, statyan commented on client/src/states/home/template.html
> +  });
Why template handles logic? All JS should be placed into corresponding controller

2017-03-23 20:38 UTC, statyan commented on server/models/Course.js
> +};
Why not to export Course itself? Is it necessary to wrap it into object ?

2017-03-23 20:38 UTC, statyan commented on server/models/Recenttasks.js
> +var RecenttasksSchema = new mongoose.Schema({
Please keep using camelCase for function and variables and UpperCamelCase for classes and schemas. in both cases each word starting from second should start from Uppercase letter (RecentTasksSchema)

2017-03-23 20:38 UTC, statyan commented on server/routes/routes.js
> +        Lecture.find({courseId: "58d370a9734d1d3c86d14b0f"}, function(err, lectures) {
Don't forget to replace hardcoded id with, maybe, state parameter, I guess

2017-03-24 16:36 UTC, dmk1111 approved these changes
seems better now

2017-03-27 19:53 UTC, closed without merging