Changed statre structure added all states for student
fl6-team-project/ng-project pull request #8
Opened 2017-03-23 19:18 UTC by HurYur

Made a lot of changes, now states and components should have right structure

2017-03-23 21:28 UTC, statyan requested changes

2017-03-23 21:28 UTC, statyan commented on client/src/app.config.router.js
> +      template: require('./states/student/index.html')
Why not a component as the other states are ?

2017-03-23 21:28 UTC, statyan commented on client/src/components/index.js
> +  app.component('personItem', personsItemComponent);
Great idea to move components decaration out of registration to keep components/index.js clean. :+1:

2017-03-23 21:28 UTC, statyan commented on client/src/components/lectureItem/lectureItemComponent.js
> +        lectures: '=?'
Why this binding is an optional ? Does this component make sense without passing parameter?
Why binding is called 'lectures' (multiple), why component is used to display one lecture?

2017-03-23 21:28 UTC, statyan commented on client/src/states/student/studentList/component.js
> +        persons: '=?'
Should be not plural and not optional

2017-03-23 21:28 UTC, statyan commented on client/src/states/student/studentList/controller.js
> +function StudentListController($http) {
Suggest to rewrite this onto Class notation.
```
class StudentListController {

  constructor($http) {
    this.$http = $http;
}
   $onInit() {
      this.$http.get('/api/users').then((res) => {
         this.persons = res.data;
      }
   }
}
StudentListController.$inject = ['$http']
```

2017-03-24 17:49 UTC, HurYur commented on client/src/states/student/studentList/controller.js
> +function StudentListController($http) {
left it for future

2017-03-24 17:49 UTC, HurYur commented on client/src/states/student/studentList/component.js
> +        persons: '=?'
fixed

2017-03-24 17:52 UTC, HurYur commented on client/src/components/lectureItem/lectureItemComponent.js
> +        lectures: '=?'
got the main different, thanks
that was implemented as tested feature, and there was a lectureList instead
remade it to real lectureItem component

2017-03-24 17:52 UTC, HurYur commented on client/src/components/index.js
> +  app.component('personItem', personsItemComponent);
thanks))

2017-03-24 17:53 UTC, HurYur commented on client/src/app.config.router.js
> +      template: require('./states/student/index.html')
made the component to it an other states

2017-03-24 17:53 UTC, dmk1111 approved these changes
Good job, don't forget about Class notation in future

2017-03-26 09:28 UTC, merged